# Generated by Django 3.2 on 2021-06-08 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_choice_choice_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.question')),
            ],
        ),
        migrations.CreateModel(
            name='CheckChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_check', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.question')),
            ],
        ),
    ]
