# Generated by Django 3.2 on 2021-06-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_checkchoice_textchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_check',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
    ]
